RESUME = """
John Doe
Computer Science Student at State University
Bachelor of Science in Computer Science: August 2020 to May 2024
Coursework: ...

Projects:
1. Project 1 (React Native, Expo, Node.js, MongoDB, Firebase): ...
2. Project 2 (Python, Claude API): ...
...

Skills:
...
"""